wso2/cellery-distribution

installer/k8s-artefacts/global-apim/conf/api-manager.xml, installer/k8s-artefacts/global-apim/conf/resources/api_templates/velocity_template.xml, installer/k8s-artefacts/global-apim/conf/security/Owasp.CsrfGuard.Carbon.properties
> update security related configurations
=> update security related configurations

installer/k8s-artefacts/controller/08-config.yaml
> update security configurations.
=> update security configurations.

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Fix mTLS bug in installation script

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Refactor sql script path.

installer/k8s-artefacts/system/istio-crds.yaml, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Refactor istio crd and sql script path.

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Remove old artifact url and names.

installer/k8s-artefacts/system/service-nodeport.yaml, installer/scripts/cellery-runtime-deployer/README.md, installer/scripts/cellery-runtime-deployer/cellery.env.gcp, installer/scripts/cellery-runtime-deployer/cellery.env.kubeadm
=> Update git base path in env.

installer/scripts/cellery-runtime-deployer/cellery-cleanup.sh, installer/scripts/cellery-runtime-deployer/cellery.env.gcp, installer/scripts/cellery-runtime-deployer/cellery.env.kubeadm
=> Add license headers.

components/gateway/io.cellery.cell.gateway.initializer/src/main/java/io/cellery/cell/gateway/initializer/UpdateManager.java, components/gateway/io.cellery.cell.gateway.initializer/src/main/java/io/cellery/cell/gateway/initializer/utils/Constants.java
=> Fix global APIM wildcard resource path bug

installer/scripts/cellery-runtime-deployer/cellery-cleanup.sh, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Separate control plane deployment.

docker/global-apim/pom.xml, docker/microgateway/init-container/pom.xml, pom.xml
> Remove unwanted dependencies and lines from POMs
> Remove unwanted content from POMs
> Remove unused content from the POMs
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> Apache Maven 3.5.4
> JDK 1.8.0_192
> N/A
=> Remove unwanted dependencies and lines from POMs

installer/k8s-artefacts/controller/01-cluster-role.yaml, installer/k8s-artefacts/controller/08-config.yaml
> Add missing STS configs and autoscaler clusterrole.
=> add missing STS configs and autoscaler clusterrole :hammer:

docker/microgateway/init-container/Dockerfile, installer/k8s-artefacts/controller/08-config.yaml, installer/k8s-artefacts/controller/09-controller.yaml, installer/k8s-artefacts/global-apim/global-apim.yaml, installer/k8s-artefacts/observability/portal/observability-portal.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml, pom.xml
> Update the Cellery versions in preparation for Release 0.1.0
> Prepare for Release 0.1.0
> The relevant versions were updated in preparation for Release 0.1.0
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Update Cellery versions in preparation for Release 0.1.0

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Remove mTLS prompt from the deploy script

docker/global-apim/pom.xml, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=>  Update k8s paths.

pom.xml
> Add Staging Cellery Nexus Repos for Staging Release
> Add Staging Cellery Nexus Repos for Staging Release
> Add Staging Cellery Nexus Repos for Staging Release
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Add Staging Cellery Nexus Repos for Staging Release

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Add master version to k8s download path.

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh, installer/scripts/cellery-runtime-deployer/cellery.env.gcp, installer/scripts/cellery-runtime-deployer/cellery.env.kubeadm
=>  Refactor to support release version 🛠️

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Fix existing k8s support 🔨

installer/packer/minimum-runtime-images/http/preseed.cfg, installer/packer/minimum-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cleanup.sh, installer/packer/minimum-runtime-images/script/docker-k8s.sh, installer/packer/minimum-runtime-images/script/minimize.sh, installer/packer/minimum-runtime-images/script/motd.sh, installer/packer/minimum-runtime-images/script/update.sh, installer/packer/minimum-runtime-images/script/vagrant.sh, installer/packer/minimum-runtime-images/script/virtualbox.sh, installer/packer/minimum-runtime-images/ubuntu.json
=>  Add VirtaulBox and Vagrant builder for the Cellery runtime.

installer/packer/minimum-runtime-images/ubuntu.json
=> Add kube config download to packer build.

installer/packer/gapim-runtime-images/http/preseed.cfg, installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/gapim-runtime-images/script/cleanup.sh, installer/packer/gapim-runtime-images/script/docker-k8s.sh, installer/packer/gapim-runtime-images/script/minimize.sh, installer/packer/gapim-runtime-images/script/motd.sh, installer/packer/gapim-runtime-images/script/update.sh, installer/packer/gapim-runtime-images/script/vagrant.sh, installer/packer/gapim-runtime-images/script/virtualbox.sh, installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/script/docker-k8s.sh
=> Update docker version.

installer/k8s-artefacts/global-idp/conf/carbon.xml, installer/k8s-artefacts/global-idp/global-idp.yaml, installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/gapim-runtime-images/script/docker-k8s.sh, installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/docker-k8s.sh, installer/packer/minimum-runtime-images/ubuntu.json
=> Add idp to packer config.

installer/k8s-artefacts/global-idp/conf/identity/identity.xml
=> Unsecure wellknown endpoint

installer/k8s-artefacts/global-idp/global-idp.yaml
=> Update readiness probe

installer/k8s-artefacts/global-idp/conf/identity/identity.xml, installer/k8s-artefacts/global-idp/global-idp.yaml, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Add identity.xml through config map

installer/k8s-artefacts/global-idp/conf/datasources/master-datasources.xml, installer/packer/minimum-runtime-images/script/cellery.sh
=> Add idp to minimum packer script.

installer/k8s-artefacts/controller/01-cluster-role.yaml
Update cluster role for the controller
=> Update cluster role for the controller

installer/k8s-artefacts/controller/08-config.yaml
=> Add updated configmap

installer/packer/minimum-runtime-images/script/cellery.sh
=> Enable istio auto injection.

installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cellery.sh
=> Add ingress-nginx to packer scripts.

installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/ubuntu.json, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=>  Add IDP support to minimum installation - Q&D

installer/packer/minimum-runtime-images/script/docker-k8s.sh, installer/packer/minimum-runtime-images/ubuntu.json
=> Update the runtime name and the version.

installer/packer/gapim-runtime-images/script/docker-k8s.sh, installer/packer/gapim-runtime-images/ubuntu.json
=> Update all in one packer.

installer/k8s-artefacts/global-apim/conf/carbon.xml, installer/k8s-artefacts/global-apim/conf/identity/identity.xml, installer/k8s-artefacts/global-apim/global-apim.yaml
> When only global apim is installed, it should act as the global IDP as well. Hence these changes are required to have
=> Make changes to installation of apim to work as IDP

docker/global-apim/Dockerfile, pom.xml
=> Change AM docker base name and docker repo name

installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/script/docker-k8s.sh, installer/packer/minimum-runtime-images/ubuntu.json
=> Add hostonly network.

installer/packer/gapim-runtime-images/resources/50-cellery.yaml, installer/packer/gapim-runtime-images/script/docker-k8s.sh, installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/resources/50-cellery.yaml
=>  Add hostonly network to the virtualbox images.

installer/k8s-artefacts/system/service-nodeport.yaml, installer/packer/gapim-runtime-images/http/preseed.cfg, installer/packer/gapim-runtime-images/resources/50-cellery.yaml, installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/resources/50-cellery.yaml, installer/packer/minimum-runtime-images/ubuntu.json
=> Add static IP to the virtualbox local net.

installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cellery.sh
=> Add observability-portal config maps.

installer/packer/minimum-runtime-images/script/cellery.sh
=> cellery.sh syntax error.

installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
> Update the default k8s_version in GKE to 1.11.8-gke.5
> Pass 'release_version' to function update_control_plance_sql in celler-deploy.sh script
> Include iaas = GCP condition in mysql installation
=> fix installer issues in GCP 🛠️

installer/packer/gapim-runtime-images/ubuntu.json
=> Refactor vm name in the complete setup.

installer/k8s-artefacts/global-apim/global-apim-volatile.yaml, installer/k8s-artefacts/global-apim/persistent-volume-local-dev.yaml, installer/k8s-artefacts/mysql/mysql-deployment-volatile.yaml, installer/k8s-artefacts/mysql/mysql-persistent-volumes-local-dev.yaml
=> Add k8s artifacts to support dev and volatile modes.

installer/k8s-artefacts/observability/sp/conf/deployment.yaml
> Add observability portal configuration for authentication purposes in deployment.yaml.
=> Add Observability portal authentication configs

docker/global-apim/Dockerfile, docker/global-apim/pom.xml, docker/lightweight-idp/Dockerfile, docker/lightweight-idp/pom.xml
=> Formatting changes

docker/global-apim/pom.xml, docker/lightweight-idp/Dockerfile, docker/lightweight-idp/pom.xml, pom.xml
> Add post IDP initializer to lightweight IDP and APIM images
=> Add post IDP initializer to lightweight IDP and APIM images

docker/global-apim/global-apim-container-base/Dockerfile, docker/global-apim/global-apim-container-base/init.sh, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=>  Add APIM base Docker image

docker/global-apim/pom.xml, docker/lightweight-idp/pom.xml, docker/microgateway/init-container-base/pom.xml, docker/microgateway/init-container/pom.xml, docker/microgateway/microgateway-container/pom.xml
> Release build fails in the deploy phase with the spotify maven plugin due to an incompatibility with the maven version.
=> Disable docker plugin to avoid release build failure

installer/packer/minimum-runtime-images/script/cellery.sh
=> Add APIM config maps to minimum setup.

installer/packer/minimum-runtime-images/script/cellery.sh
=> Add Grafana config maps.

README.md
=> Update the distribution version.

installer/k8s-artefacts/global-apim/global-apim-volatile.yaml, installer/k8s-artefacts/global-apim/global-apim.yaml
=> Update the readiness probe.

installer/k8s-artefacts/mysql/mysql-deployment.yaml
- Add readinessProbe for mysql deployment
=> Add readinessProbe for mysql deployment

Makefile
> Contains modifications docker targets to build docker images without the spotify maven plugin.
=> Modify docker build make target to remove spotify plugin

components/gateway/io.cellery.cell.gateway.initializer/src/main/java/io/cellery/cell/gateway/initializer/UpdateManager.java, components/gateway/io.cellery.cell.gateway.initializer/src/main/java/io/cellery/cell/gateway/initializer/beans/controller/API.java, components/gateway/io.cellery.cell.gateway.initializer/src/main/java/io/cellery/cell/gateway/initializer/utils/Constants.java
- Add unauthenticated API support
=> Add unauthenticated API support

installer/k8s-artefacts/global-apim/conf/api-manager.xml, installer/k8s-artefacts/global-apim/conf/identity/entitlement.properties, installer/k8s-artefacts/global-apim/conf/registry.xml, installer/k8s-artefacts/global-idp/conf/identity/entitlement.properties
Modify configs to minimize delays in APIM and IDP startup.
=> Tinker configs to reduce startup delays

installer/k8s-artefacts/global-apim/conf/api-manager.xml, installer/k8s-artefacts/global-apim/conf/registry.xml, installer/k8s-artefacts/mysql/mysql-deployment-volatile.yaml, installer/packer/gapim-runtime-images/script/cellery.sh
> Disable advanced throttling in local setup and revert unwanted config modifications.
=> turn off adv. throttling in local setup

installer/k8s-artefacts/global-apim/conf/api-manager.xml
> Disable default Analytics in APIM.
=> Disable default APIM analytics

pom.xml
> Updates the staging repository versions for the release
=> Update staging repos for release

pom.xml
> Update observability version after 0.2.2 release
=> Update observability version in parent pom

installer/k8s-artefacts/mysql/mysql-deployment-volatile.yaml
This is part of the fix of wso2-cellery/sdk/issues/373.
=> Fix cli setup failure on existing gcp cluster without persistence

installer/k8s-artefacts/controller/08-config.yaml
> Add `enable-autoscaling` to mesh-controller config map.
=> add enable-autoscaling flag

installer/k8s-artefacts/controller/01-cluster-role.yaml, installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cellery.sh, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
Add knative serving deployment
=> Add knative serving deployment

installer/k8s-artefacts/system/knative-serving.yaml
=> Add knative-serving yaml

installer/k8s-artefacts/controller/09-config.yaml
=> Update controller config

installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cellery.sh, installer/scripts/cellery-runtime-deployer/cellery-deploy.sh
=> Update controller yamls

installer/packer/minimum-runtime-images/script/cellery.sh
Remove knative installation from local basic setup.
=> Remove knative installation from local basic setup

installer/k8s-artefacts/controller/11-controller.yaml, installer/k8s-artefacts/global-idp/global-idp.yaml, installer/k8s-artefacts/mysql/mysql-deployment-volatile.yaml, installer/k8s-artefacts/mysql/mysql-deployment.yaml, installer/k8s-artefacts/nfs/nfs-server.yaml, installer/k8s-artefacts/observability/grafana/k8s-metrics-grafana.yaml, installer/k8s-artefacts/observability/portal/observability-portal.yaml, installer/k8s-artefacts/observability/prometheus/k8s-metrics-prometheus.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml, installer/packer/gapim-runtime-images/script/docker-k8s.sh, installer/packer/minimum-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/docker-k8s.sh
=> Upgrade k8s version to 1.14.3

installer/k8s-artefacts/metrics-server/aggregated-metrics-reader.yaml, installer/k8s-artefacts/metrics-server/auth-delegator.yaml, installer/k8s-artefacts/metrics-server/auth-reader.yaml, installer/k8s-artefacts/metrics-server/metrics-apiservice.yaml, installer/k8s-artefacts/metrics-server/metrics-server-deployment.yaml, installer/k8s-artefacts/metrics-server/metrics-server-service.yaml, installer/k8s-artefacts/metrics-server/resource-reader.yaml
Add metric server yamf files to k8s-artifacts.
=> Add metric server to k8s-artifacts

installer/packer/gapim-runtime-images/script/cellery.sh
Remove knative from complete setup
=> Remove knative from complete setup

installer/k8s-artefacts/observability/sp/sp-worker.yaml
> Adds permission to list the CRDs and watch cell resources using K8s client.
=> Add permissions to cells and CRDs in service account

installer/k8s-artefacts/controller/01-cluster-role.yaml
Add jobs to the controller cluster roles
=> Add jobs to the controller cluster roles

installer/packer/gapim-runtime-images/script/cellery.sh
Add idp configs to complete vm image
=> Add idp configs to complete vm image

installer/packer/gapim-runtime-images/script/cellery.sh
Add missing idp config replace command to complete vm
=> Add missing idp config replace command to complete vm

installer/k8s-artefacts/controller/09-config.yaml
> Set enable-autoscaling flag to true by default.
=> Enable autoscaling by default in cellery-config

installer/k8s-artefacts/system/mandatory.yaml
Add service entry for maven repo
=> Add service entry for maven repo

pom.xml
Update staging urls for 0.3.0 release
=> Update staging urls for 0.3.0 release

installer/k8s-artefacts/controller/11-controller.yaml
=> Update docker tag

installer/k8s-artefacts/controller/09-config.yaml, installer/k8s-artefacts/controller/11-controller.yaml, installer/k8s-artefacts/global-apim/global-apim-volatile.yaml, installer/k8s-artefacts/global-apim/global-apim.yaml, installer/k8s-artefacts/global-idp/global-idp.yaml, installer/k8s-artefacts/observability/portal/observability-portal.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml, installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/ubuntu.json, pom.xml
This reverts commit 2f6b6a9128ee292b8d59849cc7a31711ac12238d.
=> Revert "Update artifact versions for release v0.3.1"

installer/k8s-artefacts/system/istio-crds.yaml, installer/k8s-artefacts/system/istio-demo-cellery-auth.yaml, installer/k8s-artefacts/system/istio-demo-cellery.yaml, installer/k8s-artefacts/system/knative-serving.yaml
Upgrade to istio-1.2.2 and knative-serving-0.7.1
=> Upgrade to istio-1.2.2 and knative-serving-0.7.1

installer/k8s-artefacts/system/knative-serving-crds.yaml, installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cellery.sh
Add seperate knative crds yaml
=> Add seperate knative crds yaml

installer/packer/gapim-runtime-images/script/cellery.sh, installer/packer/minimum-runtime-images/script/cellery.sh
Fix applying controller yamls to packer build
=> Fix applying controller yamls to packer build

installer/k8s-artefacts/controller/10-config.yaml
Add zipkin address configuration to cellery configmap
=> Add zipkin address configuration to cellery configmap

installer/k8s-artefacts/controller/10-config.yaml
Update zipkin address to wso2sp-worker
=> Update zipkin address to wso2sp-worker

installer/helm/cellery-runtime/charts/apim/templates/wso2apim-ingress.yaml, installer/helm/cellery-runtime/charts/apim/values.yaml, installer/helm/cellery-runtime/charts/mysql/templates/local-persistent-volume.yaml, installer/helm/cellery-runtime/charts/mysql/values.yaml, installer/helm/cellery-runtime/charts/observability-portal/values.yaml, installer/helm/cellery-runtime/charts/sp-worker/values.yaml, installer/helm/cellery-runtime/values.yaml, installer/helm/cleanup.sh, installer/helm/helm-service-account.yaml, installer/helm/ingress-controller/values.yaml, installer/helm/install.sh
=> Helm installer with parent chart

installer/helm/knative-crd/templates/knative-serving-crds.yaml
=> Remove extra helm configs.

installer/helm/cellery-runtime/charts/idp/templates/identity-server-ingress.yaml, installer/helm/cellery-runtime/charts/idp/templates/identity-server-service.yaml
=> Refactor wso2is-service name to idp.

installer/helm/cellery-runtime/charts/apim/templates/identity-server-service.yaml
=> Fix the deployment name of idp service.

installer/k8s-artefacts/telepresence/telepresence-incell.yaml, installer/k8s-artefacts/telepresence/telepresence.yaml
> Add telepresence related k8s artefacts for cell testing
=> Add telepresence k8s artifacts for cell testing

installer/k8s-artefacts/observability/sp/sp-worker.yaml
> Update Stream Processor permissions
> The new Component Event Source directly accesses the CRD. Therefore, get permission is required and list is not used. Therefore, the permissions were updated.
> Update Stream Processor permissions
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> wso2-cellery/mesh-observability#62
> N/A
> N/A
> N/A
=> Update Stream Processor permissions

installer/k8s-artefacts/telepresence/telepresence-deployment.yaml
> Contains improvements  to telepresesence yaml file used for in-cell testing.
=> Improve telepresence deployment yaml

installer/k8s-artefacts/observability/sp/sp-worker.yaml, installer/packer/minimum-runtime-images/script/cellery.sh
> Remove mixer adapter from packer minimum setup
> Remove mixer adapter from packer minimum setup
> Remove mixer adapter from packer minimum setup
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Remove mixer adapter from packer minimum setup

installer/k8s-artefacts/observability/mixer-adapter/mixer-adapter.yaml
> Update SP mixer adapter metric instance
> Update SP mixer adapter metric instance
> Update SP mixer adapter metric instance
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Update SP mixer adapter metric instance

installer/k8s-artefacts/telepresence/telepresence-cell.yaml
>Update telepresence yaml with new structure
=> Update telepresence yaml with new structure

installer/helm/cellery-runtime/charts/apim/confs/apim/api-manager.xml, installer/k8s-artefacts/global-apim/conf/api-manager.xml
> Enable showing multiple versions of same api
=> Enable showing multiple versions of same api

components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/utils/RequestProcessor.java, installer/helm/cellery-runtime/charts/controller/templates/10-config.yaml, installer/k8s-artefacts/controller/10-config.yaml
> Update controller k8s artifacts for API publisher
=> Update controller k8s artifacts for api publisher

installer/k8s-artefacts/global-apim/conf/registry.xml
> Modify apim indexing configuration
=> Modify apim indexing configuration

components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/UpdateManager.java, components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/utils/Constants.java
> Set default Global API version by publisher job
=> Set default Global API version by publisher job

Makefile
> Update Makefile to push api-publisher docker image
=> Update Makefile to push api-publisher docker image

installer/helm/cellery-runtime/charts/controller/templates/10-config.yaml, installer/k8s-artefacts/controller/10-config.yaml
> Update k8s artifacts - API publisher
=> Update k8s artifacts - api publisher

installer/k8s-artefacts/telepresence/telepresence-cell.yaml
> Add env var to telepresence yaml
=> Add env var to telepresence yaml

pom.xml
=> Update depedency versions

installer/helm/cellery-runtime/charts/controller/templates/01-cluster-role.yaml, installer/k8s-artefacts/controller/01-cluster-role.yaml
Add istio authentication to cluster role
=> Add istio authentication to cluster role

installer/k8s-artefacts/system/mandatory.yaml
> Update entries related to accessing external services after the istio upgrade
=> Update entries related to accessing external services

components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/UpdateManager.java
> Modify api-publisher to support PUT, DELETE operations
=> Modify api-publisher to support PUT, DELETE operations

components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/beans/request/ApiUpdateRequest.java, components/gateway/io.cellery.cell.gateway.initializer/src/main/java/io/cellery/cell/gateway/initializer/beans/request/ApiCreateRequest.java
> Set default api version to false
=> Set default api version to false in Global API publisher

installer/k8s-artefacts/telepresence/telepresence-cell.yaml, installer/k8s-artefacts/telepresence/telepresence-deployment.yaml
> Upgrade telepresence container image version to 0.102
=> Upgrade telepresence container image version to 0.102

installer/k8s-artefacts/system/mandatory.yaml, installer/k8s-artefacts/telepresence/telepresence-cell.yaml, installer/k8s-artefacts/telepresence/telepresence-deployment.yaml
> Revert telepresence version upgrade and remove redundant service entry
=> Revert telepresence version upgrade and remove redundant service entry

components/api/io.cellery.cell.api.publisher/pom.xml, components/api/pom.xml, components/gateway/io.cellery.cell.gateway.initializer/pom.xml, components/gateway/pom.xml, components/pom.xml, docker/api-publisher/pom.xml, docker/global-apim/pom.xml, docker/lightweight-idp/pom.xml, docker/microgateway/init-container/pom.xml, docker/microgateway/microgateway-container/pom.xml, docker/microgateway/pom.xml, docker/pom.xml, pom.xml
> Revert distribution 0.4.0 release
=> Revert distribution 0.4.0 release

installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/ubuntu.json
> Update packer version to 0.5.0-SNAPSHOT
=> Update packer version to 0.5.0-SNAPSHOT

installer/k8s-artefacts/observability/mixer-adapter/mixer-adapter.yaml
Related to https://github.com/wso2-cellery/mesh-observability/pull/85
Added a config map
Changed some environment variables in mixer adapter
=> Add config map to mixer adapter and changed some envs

installer/k8s-artefacts/global-apim/global-apim.yaml, installer/k8s-artefacts/observability/observability-agent/telemetry-agent.yaml
> Add initial changes required for Observability Namespace Separation
> Add initial changes required for Observability Namespace Separation
> Add initial changes required for Observability Namespace Separation
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> wso2/cellery-observability#95
> N/A
> N/A
> N/A
=> Add initial changes required for Observability Namespace Separation

README.md, components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/UpdateManager.java
- Append port to backend production URL
=> Append port to backend production URL

installer/k8s-artefacts/observability/observability-agent/telemetry-agent.yaml, installer/k8s-artefacts/observability/observability-agent/tracing-agent.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml
> Add list namespaces permission for SP Worker
> Add list namespaces permission for SP Worker
> Add list namespaces permission for SP Worker
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Add list namespaces permission for SP Worker

installer/helm/cellery-runtime/charts/controller/templates/12-controller.yaml, installer/helm/cellery-runtime/charts/controller/templates/13-webhook.yaml, installer/k8s-artefacts/controller/12-controller.yaml, installer/k8s-artefacts/controller/13-webhook.yaml
Add admission webhook deployment
=> Add admission webhook deployment

installer/k8s-artefacts/observability/observability-agent/telemetry-agent.yaml, installer/k8s-artefacts/observability/sp/conf/deployment.yaml
> Update Istio Metric Instance and remove unused SP configurations and datasources
> Update Istio Metric Instance and remove unused SP configurations and datasources
>Update Istio Metric Instance and remove unused SP configurations and datasources
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Update Istio Metric Instance and remove unused SP configurations and datasources

installer/k8s-artefacts/observability/portal/observability-portal.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml
> Update probes and update strategies of observability deployments
> Update probes and update strategies of observability deployments
> Update probes and update strategies of observability deployments
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Update probes and update strategies of observability deployments

installer/helm/cellery-runtime/charts/controller/templates/12-controller.yaml, installer/helm/cellery-runtime/charts/controller/templates/13-webhook.yaml, installer/k8s-artefacts/controller/12-controller.yaml, installer/k8s-artefacts/controller/13-webhook.yaml
Remove latest tag from controller and webhook deployment
=> Remove latest tag from controller and webhook deployment

Makefile, components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/UpdateManager.java
> modify global API property 'cell_name' with cell namespace
=> modify global API property 'cell_name' with cell namespace

installer/k8s-artefacts/observability/portal/observability-portal.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml
> Add SP tracing and k8s info receiver ports
> Add SP tracing and k8s info receiver ports
> Add SP tracing and k8s info receiver ports
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Add SP tracing and k8s info receiver ports

installer/k8s-artefacts/observability/observability-agent/kube-agent.yaml
Add observability kube-agent deployment
=> Add observability kube-agent deployment

installer/k8s-artefacts/observability/observability-agent/kube-agent.yaml, installer/k8s-artefacts/observability/observability-agent/telemetry-agent.yaml, installer/k8s-artefacts/observability/observability-agent/tracing-agent.yaml, installer/k8s-artefacts/observability/sp/conf/deployment.yaml
> Refactor Cellery Auth Configuration to support the new Cellery auth model
> Refactor Cellery Auth Configuration
> Refactor Cellery Auth Configuration
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Refactor Cellery Auth Configuration

installer/k8s-artefacts/observability/observability-agent/telemetry-agent.yaml, installer/k8s-artefacts/observability/observability-agent/tracing-agent.yaml, installer/k8s-artefacts/observability/portal/observability-portal.yaml, installer/k8s-artefacts/observability/sp/sp-worker.yaml
> Remove unwanted SP Worker permissions
> Remove unwanted SP Worker permissions
> Remove unwanted SP Worker permissions
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Remove unwanted SP Worker permissions

installer/k8s-artefacts/observability/sp/conf/deployment.yaml
> Add SP Worker local runtime ID configuration
> Add SP Worker local runtime ID configuration
> Add SP Worker local runtime ID configuration
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Add SP Worker local runtime ID configuration

components/api/io.cellery.cell.api.publisher/pom.xml, components/api/pom.xml, components/gateway/io.cellery.cell.gateway.initializer/pom.xml, components/gateway/pom.xml, components/pom.xml, docker/api-publisher/pom.xml, docker/global-apim/pom.xml, docker/lightweight-idp/pom.xml, docker/microgateway/init-container/pom.xml, docker/microgateway/microgateway-container/pom.xml, docker/microgateway/pom.xml, docker/pom.xml, installer/packer/gapim-runtime-images/ubuntu.json, installer/packer/minimum-runtime-images/ubuntu.json, pom.xml
This reverts commit b6ac7ca0a623e53a6b749b33a3b5246054675481.
Revert "[WSO2 Release] [Jenkins #350] [Release 0.6.0] prepare for next development iteration"
This reverts commit 84cd1c965595d762736242be1a05507c776e7d0c.
Revert "[WSO2 Release] [Jenkins #350] [Release 0.6.0] prepare release v0.6.0"
This reverts commit 02856bebc66977e1a33385aefc40bc95aa735daf.
Revert "Update artifact versions for release v0.6.0"
This reverts commit 2d8ef57f0a3d5dd9364de2b9b2ea97a8b2fd6aee.
> Describe how you are implementing the solutions. Include an …
=> Revert 0.6.0 commits

installer/k8s-artefacts/minikube/calico.yaml
Add calico network policy yaml for minikube
=> Add calico network policy yaml for minikube
